name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1510-1.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1505-2.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1515-1.png
    - assets/page-1/images/group-199.png
    - assets/page-1/images/group-170.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/auto-group-xyph.png
    - assets/page-1/images/group-170-UCP.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1513-1.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/nounlock1911126.png
    - assets/page-1/images/vector-eCX.png
    - assets/page-1/images/vector-zy5.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/group-182.png
    - assets/page-1/images/vector-ryD.png
    - assets/page-1/images/group-170-mqH.png
    - assets/page-1/images/group-182-hU3.png
    - assets/page-1/images/image-17-bg.png
    - assets/page-1/images/group-199-6XR.png
    - assets/page-1/images/group-3.png
    - assets/page-1/images/vector-vgo.png
    - assets/page-1/images/group-170-BCj.png
    - assets/page-1/images/group-170-Pbd.png
    - assets/page-1/images/auto-group-nfhr.png
    - assets/page-1/images/group-170-VwV.png
    - assets/page-1/images/group-182-qXV.png
    - assets/page-1/images/group-209.png
    - assets/page-1/images/group-170-PRh.png
    - assets/page-1/images/vector-aY7.png
    - assets/page-1/images/group-170-Mqh.png
    - assets/page-1/images/group-182-MYB.png
    - assets/page-1/images/vector-phu.png
    - assets/page-1/images/vector-Pps.png
    - assets/page-1/images/group-3-gL7.png
    - assets/page-1/images/group-182-1DH.png
    - assets/page-1/images/group-169.png
    - assets/page-1/images/vector-YuD.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/vector-kMM.png
    - assets/page-1/images/master-card-logo.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1508-1.png
    - assets/page-1/images/vector-d19.png
    - assets/page-1/images/credit-card-icon.png
    - assets/page-1/images/group-182-rY7.png
    - assets/page-1/images/group-170-FT5.png
    - assets/page-1/images/group-170-HXV.png
    - assets/page-1/images/group-3-YMV.png
    - assets/page-1/images/group-162.png
    - assets/page-1/images/vector-Xcj.png
    - assets/page-1/images/auto-group-l2et.png
    - assets/page-1/images/auto-group-chqj.png
    - assets/page-1/images/vector-5q1.png
    - assets/page-1/images/auto-group-e2d5.png
    - assets/page-1/images/vector-j7V.png
    - assets/page-1/images/group-162-BHZ.png
    - assets/page-1/images/image-10-bg.png
    - assets/page-1/images/group-162-sXd.png
    - assets/page-1/images/vector-xEB.png
    - assets/page-1/images/vector-8NK.png
    - assets/page-1/images/group-170-fzX.png
    - assets/page-1/images/auto-group-j591.png
    - assets/page-1/images/group-170-PvX.png
    - assets/page-1/images/vector-R5q.png
    - assets/page-1/images/group.png
    - assets/page-1/images/card-icon.png
    - assets/page-1/images/group-182-T2X.png
    - assets/page-1/images/group-199-1GK.png
    - assets/page-1/images/group-201.png
    - assets/page-1/images/group-182-xgf.png
    - assets/page-1/images/group-170-psH.png
    - assets/page-1/images/group-170-qro.png
    - assets/page-1/images/group-170-aHm.png
    - assets/page-1/images/vector-84P.png
    - assets/page-1/images/vector-x3R.png
    - assets/page-1/images/auto-group-589d.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/group-182-c7y.png
    - assets/page-1/images/group-170-MbM.png
    - assets/page-1/images/group-170-vPZ.png
    - assets/page-1/images/group-247.png
    - assets/page-1/images/vector-X3D.png
    - assets/page-1/images/vector-1j5.png
    - assets/page-1/images/rectangle-10.png
    - assets/page-1/images/group-182-fmZ.png
    - assets/page-1/images/group-266.png
    - assets/page-1/images/group-245.png
    - assets/page-1/images/vector-KiX.png
    - assets/page-1/images/image-15-bg.png
    - assets/page-1/images/group-170-Jv3.png
    - assets/page-1/images/group-170-brX.png
    - assets/page-1/images/group-199-MuZ.png
    - assets/page-1/images/group-170-vBy.png
    - assets/page-1/images/rectangle-10-UjH.png
    - assets/page-1/images/group-199-qpj.png
    - assets/page-1/images/rectangle-7.png
    - assets/page-1/images/rectangle-8.png
    - assets/page-1/images/rectangle-4.png
    - assets/page-1/images/group-199-6Vm.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/rectangle-5.png
    - assets/page-1/images/vector-Vno.png
    - assets/page-1/images/product3.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1515-1-dT5.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1508-1-ijR.png
    - assets/page-1/images/vector-UyV.png
    - assets/page-1/images/rectangle-6.png
    - assets/page-1/images/vector-R83.png
    - assets/page-1/images/group-184.png
    - assets/page-1/images/group-229.png
    - assets/page-1/images/vector-tXR.png
    - assets/page-1/images/group-170-oPV.png
    - assets/page-1/images/auto-group-ldts.png
    - assets/page-1/images/group-170-LuD.png
    - assets/page-1/images/group-185.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1649-1.png
    - assets/page-1/images/vector-a6s.png
    - assets/page-1/images/auto-group-2bsx.png
    - assets/page-1/images/group-231.png
    - assets/page-1/images/group-182-AU7.png
    - assets/page-1/images/group-170-HaP.png
    - assets/page-1/images/group-182-fjM.png
    - assets/page-1/images/vector-waP.png
    - assets/page-1/images/image-9-bg.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1513-1-bzw.png
    - assets/page-1/images/rectangle-60.png
    - assets/page-1/images/ellipse-13.png
    - assets/page-1/images/auto-group-w7nf.png
    - assets/page-1/images/group-170-VZ1.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/vector-1Hh.png
    - assets/page-1/images/rectangle-45.png
    - assets/page-1/images/auto-group-ffpb.png
    - assets/page-1/images/group-183.png
    - assets/page-1/images/group-170-fVR.png
    - assets/page-1/images/group-182-foV.png
    - assets/page-1/images/auto-group-ys1q.png
    - assets/page-1/images/vector-gib.png
    - assets/page-1/images/auto-group-s27h.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1505-2-oXV.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/image-17-bg-XTV.png
    - assets/page-1/images/vector-GAB.png
    - assets/page-1/images/rectangle-42.png
    - assets/page-1/images/group-182-Vaf.png
    - assets/page-1/images/group-170-KQK.png
    - assets/page-1/images/ellipse-14.png
    - assets/page-1/images/rectangle-45-2qD.png
    - assets/page-1/images/group-170-o3V.png
    - assets/page-1/images/group-183-ZVR.png
    - assets/page-1/images/rectangle-31.png
    - assets/page-1/images/image-15-bg-K8j.png
    - assets/page-1/images/auto-group-ja8f.png
    - assets/page-1/images/glass-bottle-mockups-for-food-and-beverage-packaging-cover-2-bg.png
    - assets/page-1/images/group-182-3VH.png
    - assets/page-1/images/vector-3n7.png
    - assets/page-1/images/group-170-n2B.png
    - assets/page-1/images/vector-KRH.png
    - assets/page-1/images/rectangle-48.png
    - assets/page-1/images/ellipse-12-uz7.png
    - assets/page-1/images/icsignalcellularconnectednointernet2bar48px.png
    - assets/page-1/images/ellipse-14-BcB.png
    - assets/page-1/images/vector-81d.png
    - assets/page-1/images/vector-zHD.png
    - assets/page-1/images/ellipse-13-72P.png
    - assets/page-1/images/icsignalwifistatusbar4bar26x24px.png
    - assets/page-1/images/rectangle-31-iNs.png
    - assets/page-1/images/vector-bnf.png
    - assets/page-1/images/vector-g5D.png
    - assets/page-1/images/group-197.png
    - assets/page-1/images/vector-bRZ.png
    - assets/page-1/images/vector-9hy.png
    - assets/page-1/images/vector-r2b.png
    - assets/page-1/images/rectangle-47.png
    - assets/page-1/images/vector-mYB.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/vector-i5d.png
    - assets/page-1/images/vector-sa7.png
    - assets/page-1/images/group-170-2C7.png
    - assets/page-1/images/group-182-d75.png
    - assets/page-1/images/group-180.png
    - assets/page-1/images/mask-group-Z3D.png
    - assets/page-1/images/rectangle-46.png
    - assets/page-1/images/icbatterychargingfull48px.png
    - assets/page-1/images/ellipse-13-2PR.png
    - assets/page-1/images/rectangle-4-PiP.png
    - assets/page-1/images/vector-9Dh.png
    - assets/page-1/images/vector-wps.png
    - assets/page-1/images/vector-QiT.png
    - assets/page-1/images/vector-Noh.png
    - assets/page-1/images/vector-pg7.png
    - assets/page-1/images/group-170-nPH.png
    - assets/page-1/images/group-199-VS7.png
    - assets/page-1/images/group-170-vgP.png
    - assets/page-1/images/group-170-eFH.png
    - assets/page-1/images/rectangle-8-AUX.png
    - assets/page-1/images/group-170-c5V.png
    - assets/page-1/images/group-220.png
    - assets/page-1/images/group-220-iWB.png
    - assets/page-1/images/mask-group-K6P.png
    - assets/page-1/images/group-170-LMV.png
    - assets/page-1/images/group-162-Ca3.png
    - assets/page-1/images/group-162-7uq.png
    - assets/page-1/images/group-170-Rb5.png
    - assets/page-1/images/group-170-kEb.png
    - assets/page-1/images/ellipse-12-NCf.png
    - assets/page-1/images/ellipse-14-4GF.png
    - assets/page-1/images/vector-B5y.png
    - assets/page-1/images/vector-rnK.png
    - assets/page-1/images/group-182-HKm.png
    - assets/page-1/images/group-199-Xcs.png
    - assets/page-1/images/auto-group-xzoh.png
    - assets/page-1/images/group-182-zUP.png
    - assets/page-1/images/group-3-xbH.png
    - assets/page-1/images/mask-group-8vK.png
    - assets/page-1/images/group-3-rm5.png
    - assets/page-1/images/group-3-Gm5.png
    - assets/page-1/images/rectangle-7-xP1.png
    - assets/page-1/images/group-3-Bd1.png
    - assets/page-1/images/group-170-wKD.png
    - assets/page-1/images/group-170-gSj.png
    - assets/page-1/images/vector-JAK.png
    - assets/page-1/images/rectangle-6-yom.png
    - assets/page-1/images/rectangle-9-GVM.png
    - assets/page-1/images/group-162-Qud.png
    - assets/page-1/images/group-199-VeF.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1505-2-tzK.png
    - assets/page-1/images/group-3-xPq.png
    - assets/page-1/images/group-162-qhq.png
    - assets/page-1/images/group-170-AiK.png
    - assets/page-1/images/rectangle-10-Wwq.png
    - assets/page-1/images/group-162-D19.png
    - assets/page-1/images/group-162-Q4f.png
    - assets/page-1/images/group-199-f9Z.png
    - assets/page-1/images/group-182-JyD.png
    - assets/page-1/images/group-162-ChD.png
    - assets/page-1/images/image-4-xqD.png
    - assets/page-1/images/auto-group-hpoh.png
    - assets/page-1/images/image-6-qB5.png
    - assets/page-1/images/auto-group-57uk.png
    - assets/page-1/images/image-5-1eo.png
    - assets/page-1/images/rectangle-5-yG3.png
    - assets/page-1/images/group-170-NST.png
    - assets/page-1/images/group-182-vTy.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/group-170-aPh.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1505-2-NT9.png
    - assets/page-1/images/vector-AoZ.png
    - assets/page-1/images/image-4-ftT.png
    - assets/page-1/images/group-170-xf9.png
    - assets/page-1/images/vector-6dm.png
    - assets/page-1/images/vector-THq.png
    - assets/page-1/images/image-4-ayM.png
    - assets/page-1/images/image-6-Mno.png
    - assets/page-1/images/group-3-BXD.png
    - assets/page-1/images/group-3-Zd1.png
    - assets/page-1/images/vector-tx7.png
    - assets/page-1/images/auto-group-qxto.png
    - assets/page-1/images/image-5-Fpj.png
    - assets/page-1/images/image-6-xJs.png
    - assets/page-1/images/group-3-NF9.png
    - assets/page-1/images/vector-CCP.png
    - assets/page-1/images/image-5-B5H.png
    - assets/page-1/images/group-162-Kx3.png
    - assets/page-1/images/group-162-vK1.png
    - assets/page-1/images/group-3-7Gs.png
    - assets/page-1/images/group-199-abh.png
    - assets/page-1/images/vector-eeb.png
    - assets/page-1/images/vector-wvw.png
    - assets/page-1/images/whatsapp-image-2024-02-15-at-1649-1-xhM.png
    - assets/page-1/images/vector-b6F.png
    - assets/page-1/images/image-4-cud.png
    - assets/page-1/images/group-3-TVH.png
    - assets/page-1/images/group-162-iLf.png
    - assets/page-1/images/vector-3if.png
    - assets/page-1/images/vector-GM5.png
    - assets/page-1/images/vector-FFu.png
    - assets/page-1/images/vector-Gis.png
    - assets/page-1/images/group-182-1X5.png
    - assets/page-1/images/vector-UDD.png
    - assets/page-1/images/vector-UET.png
    - assets/page-1/images/group-170-RMR.png
    - assets/page-1/images/vector-6xF.png
    - assets/page-1/images/image-18-bg.png
    - assets/page-1/images/vector-BSf.png
    - assets/page-1/images/map-marker.png
    - assets/page-1/images/group-170-RgT.png
    - assets/page-1/images/vector-Cmm.png
    - assets/page-1/images/vector-2HM.png
    - assets/page-1/images/vector-HSf.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
